# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-08-26 21:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0006_department'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='departman',
        ),
        migrations.RemoveField(
            model_name='department',
            name='post',
        ),
        migrations.AddField(
            model_name='department',
            name='department_name',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='department',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='post.Department'),
            preserve_default=False,
        ),
    ]
